application:
  security:
    jwt:
      secret-key: cf0e0500f818df14ba9121585cae3bc9653bd0f3543b5c67d3f218babdb703e7
      expiration: '86400000'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/cine_box?allowPublicKeyRetrieval=true&useSSL=false
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: 'true'
        use_sql_comments: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  application:
    name: cineBox

paypal:
  clientId: AWNKz5fg5qVljb8AzEHuv7t9XE7i3husY4tSBHMWNT2eoq2hVsA-3n2ZuyVIsQqLhmF2Yu4P7bZDR89m
  secret: EPjEZbHYk-eJcAhUataqv0CLSdriQXKRrmEDShKW-G5nv5VEch44hXBYca4u61UZnaJZEX3QKSlWJRPw
  mode: sandbox